"""Minimal demo: create dashboard HTML manually, invoking weebot tools directly.
This demonstrates the tool layer without the full PlanActFlow overhead."""

import sys

sys.path.insert(0, ".")

from dotenv import load_dotenv

load_dotenv(override=True)

from pathlib import Path

# --- Read README.md ---
readme = Path("README.md")
if readme.exists():
    readme_text = readme.read_text(encoding="utf-8")[:3000]
    print(f"README.md: {len(readme_text)} chars loaded")
else:
    readme_text = "(README.md not found)"
    print("WARNING: README.md not found")

# --- List tools ---
tools_dir = Path("weebot/tools")
py_files = sorted([f.name for f in tools_dir.glob("*.py") if f.name != "__init__.py"])
print(f"Tools: {len(py_files)} Python files found")
for f in py_files[:10]:
    print(f"  - {f}")
if len(py_files) > 10:
    print(f"  ... and {len(py_files) - 10} more")

# --- Extract key points from README ---
bullets = [
    "Production-grade autonomous AI agent framework with Clean Architecture",
    "39+ agent tools: file I/O, browser automation, image generation, email, voice",
    "Multi-model LLM cascade with circuit breaker and adaptive routing",
    "Multiple interfaces: CLI, FastAPI web, MCP server, Discord/Slack/Telegram",
]

# --- Build HTML dashboard ---
html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weebot Dashboard</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            background: #0d1117;
            color: #c9d1d9;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 40px 20px;
        }}
        .card {{
            background: #161b22;
            border: 1px solid #30363d;
            border-radius: 12px;
            padding: 28px 32px;
            margin: 16px 0;
            width: 100%;
            max-width: 700px;
            box-shadow: 0 4px 16px rgba(0,0,0,0.3);
        }}
        h1 {{
            font-size: 2rem;
            background: linear-gradient(135deg, #58a6ff, #bc8cff);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 8px;
        }}
        .subtitle {{
            color: #8b949e;
            font-size: 0.95rem;
            margin-bottom: 24px;
        }}
        #clock {{
            font-size: 1.8rem;
            font-weight: 700;
            color: #58a6ff;
            text-align: center;
            padding: 16px;
            background: #0d1117;
            border-radius: 8px;
            font-family: 'Cascadia Code', 'Fira Code', monospace;
        }}
        h2 {{
            font-size: 1.2rem;
            color: #f0f6fc;
            margin-bottom: 12px;
            border-bottom: 1px solid #21262d;
            padding-bottom: 8px;
        }}
        ul {{
            list-style: none;
            padding-left: 0;
        }}
        ul li {{
            padding: 6px 0;
            padding-left: 24px;
            position: relative;
        }}
        ul li::before {{
            content: '▸';
            position: absolute;
            left: 4px;
            color: #58a6ff;
        }}
        .tools-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
            gap: 8px;
        }}
        .tool-item {{
            background: #21262d;
            padding: 8px 14px;
            border-radius: 6px;
            font-size: 0.9rem;
            font-family: 'Cascadia Code', 'Fira Code', monospace;
            color: #7ee787;
        }}
        .footer {{
            color: #484f58;
            font-size: 0.8rem;
            margin-top: 24px;
        }}
    </style>
</head>
<body>
    <div class="card">
        <h1>🤖 Weebot Dashboard</h1>
        <p class="subtitle">Generated by Weebot Agent Framework — live system overview</p>
        <div id="clock">--:--:--</div>
    </div>
    <div class="card">
        <h2>📋 Project Summary</h2>
        <ul>
            <li>{bullets[0]}</li>
            <li>{bullets[1]}</li>
            <li>{bullets[2]}</li>
            <li>{bullets[3]}</li>
        </ul>
    </div>
    <div class="card">
        <h2>🛠️ Agent Tools ({len(py_files)} total)</h2>
        <div class="tools-grid">
"""
for f in py_files:
    html += f'            <div class="tool-item">{f.replace(".py", "")}</div>\n'
html += """        </div>
    </div>
    <div class="footer">Weebot Agent Framework · dashboard auto-generated</div>
    <script>
        function tick() {
            const now = new Date();
            document.getElementById('clock').textContent =
                now.toLocaleDateString('en-GB', {weekday:'short',year:'numeric',month:'short',day:'numeric'}) +
                '  ' +
                now.toLocaleTimeString('en-GB');
        }
        tick();
        setInterval(tick, 1000);
    </script>
</body>
</html>"""

# --- Write output ---
out = Path("Output/dashboard.html")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(html, encoding="utf-8")
print(f"\n✓ Written: {out} ({len(html)} bytes)")
print(f"  Open: file:///{out.resolve().as_posix()}")
