"""Chain-of-Verification (CoVe) service — LLM self-verification for factual accuracy.

Implements the 4-step CoVe method from Dhuliawala et al. (2023):
1. Baseline response (already generated by the executor)
2. Plan verification questions to fact-check the draft
3. Execute verifications independently (factored — each question separately)
4. Generate final verified response

Core insight: answering verification questions WITHOUT the baseline context
(factored) yields higher accuracy than joint methods.
"""
from __future__ import annotations

import logging
import re
from typing import Any, Optional

from weebot.application.ports.llm_port import LLMPort
from weebot.domain.models.event import AgentEvent, MessageEvent

logger = logging.getLogger(__name__)


def _fmt(template: str, **kwargs: str) -> str:
    """Safely format a template with untrusted string values.

    Uses ``str.replace()`` instead of ``str.format()`` so that curly braces
    inside the values (JSON, code, math expressions like ``{x: 1}``) do not
    cause ``KeyError`` or ``ValueError``.
    """
    result = template
    for key, val in kwargs.items():
        placeholder = "{" + key + "}"
        result = result.replace(placeholder, val)
    return result


# ── Step 2: Plan verification questions ─────────────────────────────

_PLAN_VERIFICATIONS_PROMPT = """You are a fact-checker. Given a user query and an AI's response, generate a list of verification questions that test each factual claim in the response.

Rules:
- One question per distinct factual claim (dates, names, locations, statistics, causal claims, sequence of events, etc.)
- Ask about the claim directly, without referencing the AI's answer
- Prefer open-ended questions ("When did X happen?") over yes/no questions ("Did X happen in 1846?")
- Be specific — ask about concrete facts, not opinions
- Return ONLY a JSON array of strings, e.g. ["Question 1?", "Question 2?", ...]
- If there are no factual claims to verify, return []

Query: {query}

Response to fact-check:
{response}

Verification questions (JSON array):"""


# ── Step 3: Answer a single verification question (factored) ─────────

_ANSWER_VERIFICATION_PROMPT = """Answer the following question concisely and factually. If you don't know the answer, say "Unknown".

Question: {question}

Answer:"""


# ── Step 4: Cross-check and generate final verified response ─────────

_CROSS_CHECK_PROMPT = """You are a careful editor. You have:

1. A user query
2. An original AI response (may contain errors)
3. Verification questions and their answers

For each verification question, check whether the answer contradicts the original response. Then produce a corrected version.

Format your response as JSON:
{{
  "inconsistencies": [
    {{
      "claim": "the original claim that was wrong",
      "correction": "the corrected fact",
      "verification_question": "the question that exposed it"
    }}
  ],
  "corrected_response": "the full corrected response with all fixes applied"
}}

If no inconsistencies were found, return an empty inconsistencies list and the corrected_response as the original response unchanged.

Query: {query}

Original response:
{response}

Verification Q&A:
{verification_qa}

JSON response:"""


def _extract_json_array(text: str) -> list[str]:
    """Extract a JSON array from *text*, stripping markdown fences."""
    text = text.strip()
    # Strip markdown code fences
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    text = text.strip()
    try:
        import json
        result = json.loads(text)
        if isinstance(result, list):
            return [str(item) for item in result]
    except (json.JSONDecodeError, TypeError):
        pass
    # Fallback: line-by-line extraction
    lines = [l.strip("- ").strip() for l in text.split("\n") if l.strip()]
    return [l for l in lines if l.endswith("?")]


def _extract_json_object(text: str) -> dict:
    """Extract a JSON object from *text*, stripping markdown fences."""
    import json
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    text = text.strip()
    try:
        return json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return {"inconsistencies": [], "corrected_response": text}


class ChainOfVerificationService:
    """Orchestrates the 4-step CoVe pipeline.

    Uses the LLMPort for all steps.  Step 3 (Execute Verifications) is
    factored — each question is answered in a separate LLM call with no
    access to the baseline response, per the paper's best-performing variant.
    """

    def __init__(self, llm: LLMPort):
        self._llm = llm

    async def verify(
        self,
        query: str,
        response: str,
        max_questions: int = 5,
    ) -> tuple[str, list[dict]]:
        """Run the full CoVe pipeline.

        Args:
            query: The original user query / task prompt.
            response: The baseline response to fact-check.
            max_questions: Cap on verification questions (avoids token blow-up).

        Returns:
            (corrected_response, inconsistencies) where inconsistencies is
            a list of {"claim", "correction", "verification_question"} dicts.
        """
        # ── Step 2: Plan verifications ──
        questions = await self._plan_verifications(query, response)
        questions = questions[:max_questions]
        if not questions:
            logger.info("CoVe: no verification questions generated — skipping")
            return response, []

        # ── Step 3: Execute verifications (factored) ──
        qa_pairs = await self._execute_verifications(questions)

        # ── Step 4: Cross-check and final verified response ──
        corrected, inconsistencies = await self._cross_check(
            query, response, qa_pairs
        )

        logger.info(
            "CoVe: %d questions, %d inconsistencies found",
            len(questions), len(inconsistencies),
        )
        return corrected, inconsistencies

    async def _plan_verifications(self, query: str, response: str) -> list[str]:
        """Step 2: Generate verification questions from query + baseline."""
        prompt = _fmt(_PLAN_VERIFICATIONS_PROMPT,
            query=query, response=response
        )
        try:
            llm_response = await self._llm.chat(
                messages=[
                    {"role": "user", "content": prompt},
                ],
                max_tokens=500,
                temperature=0.1,
            )
            return _extract_json_array(llm_response.content)
        except Exception as exc:
            logger.warning("CoVe plan-verifications failed: %s", exc)
            return []

    async def _execute_verifications(
        self, questions: list[str],
    ) -> list[dict]:
        """Step 3: Answer each question independently (factored).

        Each question gets its own LLM call with NO baseline context.
        Runs in parallel via asyncio.gather.
        """
        import asyncio

        async def _answer_one(q: str) -> dict:
            try:
                resp = await self._llm.chat(
                    messages=[
                        {"role": "user", "content": _fmt(_ANSWER_VERIFICATION_PROMPT, question=q)},
                    ],
                    max_tokens=150,
                    temperature=0.1,
                )
                return {"question": q, "answer": resp.content.strip()}
            except Exception as exc:
                return {"question": q, "answer": f"Error: {exc}"}

        results = await asyncio.gather(*[_answer_one(q) for q in questions])
        return list(results)

    async def _cross_check(
        self, query: str, response: str, qa_pairs: list[dict],
    ) -> tuple[str, list[dict]]:
        """Step 4: Cross-check answers against baseline, produce corrected response."""
        qa_text = "\n".join(
            f"Q: {p['question']}\nA: {p['answer']}"
            for p in qa_pairs
        )
        prompt = _fmt(_CROSS_CHECK_PROMPT,
            query=query, response=response, verification_qa=qa_text,
        )
        try:
            llm_response = await self._llm.chat(
                messages=[
                    {"role": "user", "content": prompt},
                ],
                max_tokens=2000,
                temperature=0.1,
            )
            data = _extract_json_object(llm_response.content)
            corrected = data.get("corrected_response", response)
            inconsistencies = data.get("inconsistencies", [])
            return corrected, inconsistencies
        except Exception as exc:
            logger.warning("CoVe cross-check failed: %s", exc)
            return response, []
