"""SubagentRPC — lightweight RPC-based subagent invocation.

Unlike DispatchAgentsTool (full PlanActFlow sub-agents), this tool
allows writing Python scripts that call tools via a simple RPC
mechanism, collapsing multi-step pipelines into zero-context-cost turns.

The agent writes a Python script that:
1. Calls ``rpc_call("tool_name", arg1=val1, ...)``
2. Processes results
3. Returns a final result string

Inspired by Hermes Agent's delegate/parallelize system.
"""
from __future__ import annotations

import asyncio
import json
import logging
import sys
import tempfile
import traceback
from pathlib import Path
from typing import Any, Optional

from pydantic import ConfigDict, PrivateAttr

from weebot.tools.base import BaseTool, ToolResult

logger = logging.getLogger(__name__)

_RPC_SCRIPT_TEMPLATE = """\
#!/usr/bin/env python3
\"\"\"RPC subagent — generated by SubagentRPCTool.\"\"\"
import json
import sys
from typing import Any

# Available tools
_AVAILABLE_TOOLS = {tool_registry}

def rpc_call(tool_name: str, **kwargs) -> Any:
    \"\"\"Call a tool via RPC and return its result.\"\"\"
    if tool_name not in _AVAILABLE_TOOLS:
        return {{"error": f"Unknown tool: {{tool_name}}", "success": False}}

    # Print structured output for the parent to collect
    request = {{"tool": tool_name, "args": kwargs}}
    print(json.dumps(request))
    # Read the response from stdin
    response = sys.stdin.readline()
    if not response:
        return {{"error": "No response from parent", "success": False}}
    return json.loads(response)

# === USER CODE ===
{user_code}
"""


class SubagentRPCTool(BaseTool):
    """Execute a Python script that uses RPC for tool calls.

    The script can call ``rpc_call("tool_name", arg1=val1, ...)``
    to invoke any available tool.  Results are returned as JSON.

    This is a lightweight alternative to full PlanActFlow sub-agents —
    the script runs in a subprocess with minimal overhead.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    name: str = "subagent_rpc"
    description: str = (
        "Execute a Python script that calls tools via RPC. "
        "Use 'rpc_call(\"tool_name\", arg1=val1)' inside the script "
        "to invoke tools.  The script runs in an isolated subprocess "
        "with lower overhead than a full sub-agent.  Ideal for "
        "multi-step pipelines where each step is a tool call."
    )
    parameters: dict = {
        "type": "object",
        "properties": {
            "script": {
                "type": "string",
                "description": (
                    "Python code to execute. Use rpc_call() to invoke tools. "
                    "The final value of the expression or last print statement "
                    "becomes the result."
                ),
            },
            "timeout": {
                "type": "number",
                "description": "Timeout in seconds (default 60)",
            },
        },
        "required": ["script"],
    }

    _timeout: float = PrivateAttr(default=60.0)

    async def execute(  # type: ignore[override]
        self,
        script: str,
        timeout: Optional[float] = None,
        **_: object,
    ) -> ToolResult:
        effective_timeout = timeout or self._timeout

        # Build the RPC script wrapper
        # NOTE: In production, tool registration would be injected via DI
        tool_registry = json.dumps([
            "bash", "python_execute", "web_search", "file_editor",
        ])
        full_script = _RPC_SCRIPT_TEMPLATE.format(
            tool_registry=tool_registry,
            user_code=script,
        )

        # Write to temp file and execute
        try:
            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".py", delete=False, encoding="utf-8",
            ) as f:
                f.write(full_script)
                temp_path = f.name

            proc = await asyncio.create_subprocess_exec(
                sys.executable, temp_path,
                stdin=asyncio.subprocess.PIPE,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )

            try:
                stdout, stderr = await asyncio.wait_for(
                    proc.communicate(), timeout=effective_timeout,
                )
            except asyncio.TimeoutError:
                proc.kill()
                return ToolResult(
                    output="",
                    error=f"Subagent RPC timed out after {effective_timeout:.0f}s",
                )

            output = stdout.decode("utf-8", errors="replace")
            error = stderr.decode("utf-8", errors="replace")

            if proc.returncode != 0:
                return ToolResult(
                    output=output,
                    error=error or f"Exit code {proc.returncode}",
                )

            # Parse structured output lines
            result_lines = []
            for line in output.strip().split("\n"):
                line = line.strip()
                if line:
                    try:
                        parsed = json.loads(line)
                        if "tool" in parsed:
                            # RPC request — we don't execute tools here
                            # (the parent agent does that in production)
                            result_lines.append(
                                f"[RPC] Would call {parsed['tool']}: {parsed['args']}"
                            )
                        else:
                            result_lines.append(str(parsed))
                    except (json.JSONDecodeError, ValueError):
                        result_lines.append(line)

            return ToolResult(
                output="\n".join(result_lines) if result_lines else output,
            )

        except Exception as exc:
            logger.warning("Subagent RPC failed: %s", exc)
            return ToolResult(output="", error=f"Subagent RPC failed: {exc}")
        finally:
            try:
                Path(temp_path).unlink(missing_ok=True)
            except (NameError, UnboundLocalError):
                pass
