"""SubagentRPC — lightweight RPC-based subagent invocation.

Unlike DispatchAgentsTool (full PlanActFlow sub-agents), this tool
allows writing Python scripts that call tools via a simple RPC
mechanism, collapsing multi-step pipelines into zero-context-cost turns.

The agent writes a Python script that:
1. Calls ``rpc_call("tool_name", arg1=val1, ...)``
2. Processes results
3. Returns a final result string

Inspired by Hermes Agent's delegate/parallelize system.
"""
from __future__ import annotations

import asyncio
import json
import logging
import sys
import tempfile
import traceback
from pathlib import Path
from typing import Any, Optional

from pydantic import ConfigDict, PrivateAttr

from weebot.tools.base import BaseTool, ToolResult

logger = logging.getLogger(__name__)

_RPC_SCRIPT_TEMPLATE = """\
#!/usr/bin/env python3
\"\"\"RPC subagent — generated by SubagentRPCTool.\"\"\"
import json
import sys
import time
from typing import Any

# Available tools
_AVAILABLE_TOOLS = {tool_registry}

def rpc_call(tool_name: str, **kwargs) -> Any:
    \"\"\"Call a tool via RPC and return its result.\"\"\"
    if tool_name not in _AVAILABLE_TOOLS:
        return {{"error": f"Unknown tool: {{tool_name}}", "success": False}}

    # Print structured output for the parent to collect
    request = {{"tool": tool_name, "args": kwargs, "id": str(time.time())}}
    print(json.dumps(request), flush=True)
    # Read the response from stdin
    response = sys.stdin.readline()
    if not response:
        return {{"error": "No response from parent", "success": False, "tool": tool_name}}
    try:
        result = json.loads(response)
        if not result.get("success", True):
            return {{"error": result.get("error", "Unknown error"), "success": False, "tool": tool_name}}
        return result
    except json.JSONDecodeError:
        return {{"error": f"Invalid response: {{response[:100]}}", "success": False, "tool": tool_name}}

def rpc_call_parallel(tool_calls: list[dict]) -> list[Any]:
    \"\"\"Call multiple tools in parallel.

    Each item in tool_calls is a dict: {{"tool": name, "args": {{...}}}}
    Returns a list of results in the same order.
    \"\"\"
    # Print a batch request
    request = {{"_batch": True, "calls": tool_calls, "id": str(time.time())}}
    print(json.dumps(request), flush=True)
    response = sys.stdin.readline()
    if not response:
        return [{{"error": "No response", "success": False}} for _ in tool_calls]
    try:
        result = json.loads(response)
        if isinstance(result, list):
            return result
        return [result]
    except json.JSONDecodeError:
        return [{{"error": f"Invalid batch response", "success": False}} for _ in tool_calls]

def emit_result(result: Any) -> None:
    \"\"\"Emit a structured result that the parent can parse.

    Print a JSON result marker at the end of execution.
    \"\"\"
    output = {{
        "_result": True,
        "data": result,
        "duration_seconds": 0,  # Will be filled by wrapper
        "tool_calls": 0,
    }}
    print(json.dumps(output), flush=True)

# === USER CODE ===
{user_code}
"""


class SubagentRPCTool(BaseTool):
    """Execute a Python script that uses RPC for tool calls.

    The script can call ``rpc_call("tool_name", arg1=val1, ...)``
    to invoke any available tool.  Results are returned as JSON.

    This is a lightweight alternative to full PlanActFlow sub-agents —
    the script runs in a subprocess with minimal overhead.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    name: str = "subagent_rpc"
    description: str = (
        "Execute a Python script that calls tools via RPC. "
        "Use 'rpc_call(\"tool_name\", arg1=val1)' inside the script "
        "to invoke tools.  The script runs in an isolated subprocess "
        "with lower overhead than a full sub-agent.  Ideal for "
        "multi-step pipelines where each step is a tool call."
    )
    parameters: dict = {
        "type": "object",
        "properties": {
            "script": {
                "type": "string",
                "description": (
                    "Python code to execute. Use rpc_call() to invoke tools. "
                    "The final value of the expression or last print statement "
                    "becomes the result."
                ),
            },
            "timeout": {
                "type": "number",
                "description": "Timeout in seconds (default 60)",
            },
        },
        "required": ["script"],
    }

    _timeout: float = PrivateAttr(default=60.0)

    async def _rpc_loop(
        self,
        proc: asyncio.subprocess.Process,
    ) -> tuple[bytes, bytes]:
        """Run the RPC protocol: read JSON requests from stdout, write responses to stdin.

        Each line of stdout is a JSON request.  If it contains `\"tool\"` it's a
        tool call; the parent responds with a stub result so the subprocess
        doesn't deadlock.  When the subprocess emits a `_result` marker or
        stdout closes, the loop ends and we return the accumulated output.
        """
        output_chunks: list[bytes] = []
        stderr_chunks: list[bytes] = []

        async def _read_stderr() -> None:
            while True:
                chunk = await proc.stderr.read(4096)
                if not chunk:
                    break
                stderr_chunks.append(chunk)

        stderr_task = asyncio.ensure_future(_read_stderr())

        try:
            while True:
                line = await proc.stdout.readline()
                if not line:
                    break  # stdout closed → subprocess exited

                output_chunks.append(line)

                try:
                    request = json.loads(line)
                except json.JSONDecodeError:
                    continue  # Not JSON — just text output

                if "_result" in request:
                    break  # Subprocess signaled completion

                if "tool" in request or "_batch" in request:
                    # Respond with a stub result so the subprocess continues
                    response = json.dumps({
                        "success": True,
                        "output": f"[stub] tool '{request.get('tool', 'batch')}' would execute here",
                    }) + "\n"
                    proc.stdin.write(response.encode("utf-8"))
                    await proc.stdin.drain()

        except Exception:
            pass
        finally:
            stderr_task.cancel()
            try:
                await stderr_task
            except asyncio.CancelledError:
                pass

        return b"".join(output_chunks), b"".join(stderr_chunks)

    async def execute(  # type: ignore[override]
        self,
        script: str,
        timeout: Optional[float] = None,
        **_: object,
    ) -> ToolResult:
        effective_timeout = timeout or self._timeout

        # Build the RPC script wrapper
        # NOTE: In production, tool registration would be injected via DI
        tool_registry = json.dumps([
            "bash", "python_execute", "web_search", "file_editor",
        ])
        full_script = _RPC_SCRIPT_TEMPLATE.format(
            tool_registry=tool_registry,
            user_code=script,
        )

        # Write to temp file and execute
        try:
            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".py", delete=False, encoding="utf-8",
            ) as f:
                f.write(full_script)
                temp_path = f.name

            proc = await asyncio.create_subprocess_exec(
                sys.executable, temp_path,
                stdin=asyncio.subprocess.PIPE,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )

            try:
                # Run an RPC loop: read stdout line by line, execute tools,
                # write results back to stdin.  Stop when the subprocess emits
                # a _result marker or exits.
                stdout, stderr = await asyncio.wait_for(
                    self._rpc_loop(proc), timeout=effective_timeout,
                )
            except asyncio.TimeoutError:
                proc.kill()
                return ToolResult(
                    output="",
                    error=f"Subagent RPC timed out after {effective_timeout:.0f}s",
                )

            output = stdout.decode("utf-8", errors="replace")
            error = stderr.decode("utf-8", errors="replace")

            if proc.returncode != 0:
                return ToolResult(
                    output=output,
                    error=error or f"Exit code {proc.returncode}",
                )

            # Parse structured output — look for _result marker first
            result_lines = []
            for line in output.strip().split("\n"):
                line = line.strip()
                if not line:
                    continue
                try:
                    parsed = json.loads(line)
                    if parsed.get("_result"):
                        data = parsed.get("data", "")
                        result_lines.append(str(data) if not isinstance(data, str) else data)
                    elif "tool" in parsed and not parsed.get("_batch"):
                        result_lines.append(
                            f"[RPC] Would call {parsed['tool']}: {parsed.get('args', {})}"
                        )
                    elif parsed.get("_batch"):
                        calls = parsed.get("calls", [])
                        names = ", ".join(c.get("tool", "?") for c in calls)
                        result_lines.append(f"[RPC] Batch call: {names}")
                    else:
                        result_lines.append(str(parsed))
                except (json.JSONDecodeError, ValueError):
                    result_lines.append(line)

            return ToolResult(
                output="\n".join(result_lines) if result_lines else output,
            )

        except Exception as exc:
            logger.warning("Subagent RPC failed: %s", exc)
            return ToolResult(output="", error=f"Subagent RPC failed: {exc}")
        finally:
            try:
                Path(temp_path).unlink(missing_ok=True)
            except (NameError, UnboundLocalError):
                pass
