"""Example 03 — File & Shell Automation
=========================================
Demonstrates BashTool (PowerShell) and StrReplaceEditorTool working together
for a typical Windows automation task:

  Step 1  BashTool            → query system info (PS version, OS, memory)
  Step 2  StrReplaceEditorTool → scaffold a small project directory
  Step 3  StrReplaceEditorTool → edit a file in-place (str_replace)
  Step 4  BashTool            → verify the scaffold via Get-ChildItem

Requirements: Windows 11 + PowerShell (BashTool steps gracefully skipped
              if PowerShell is unavailable).

Usage:
    python examples/03_file_automation.py
"""
from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.stdout.reconfigure(encoding="utf-8")

from weebot.activity_stream import ActivityStream
from weebot.tools.bash_tool import BashTool
from weebot.tools.file_editor import StrReplaceEditorTool

# All scaffold files land inside examples/output/scaffold/
SCAFFOLD_DIR = str(Path(__file__).parent / "output" / "scaffold")


async def step_system_info(bash: BashTool, stream: ActivityStream) -> None:
    """Query basic system information via PowerShell."""
    print("🖥️   Step 1: System info via PowerShell …")
    cmd = (
        "[PSCustomObject]@{"
        "  PS       = $PSVersionTable.PSVersion.ToString();"
        "  OS       = [System.Environment]::OSVersion.VersionString;"
        "  MemoryGB = [math]::Round((Get-CimInstance Win32_PhysicalMemory |"
        "             Measure-Object -Property Capacity -Sum).Sum / 1GB, 1)"
        "} | Format-List"
    )
    result = await bash.execute(command=cmd, timeout=15)
    if result.is_error:
        print(f"  ⚠️   Skipped (PowerShell unavailable): {result.error}")
    else:
        for line in result.output.strip().splitlines():
            print(f"  {line}")
        stream.push("example-03", "tool", "bash: system info")
    print()


async def step_scaffold(editor: StrReplaceEditorTool, stream: ActivityStream) -> None:
    """Create a small project scaffold using StrReplaceEditorTool."""
    print("📁  Step 2: Creating project scaffold …")

    files: dict[str, str] = {
        f"{SCAFFOLD_DIR}/README.md": (
            "# Scaffold Project\n\n"
            "Auto-generated by weebot Example 03.\n\n"
            "## Structure\n\n```\nscaffold/\n├── README.md\n"
            "├── src/\n│   ├── __init__.py\n│   └── main.py\n"
            "└── tests/\n    └── test_main.py\n```\n"
        ),
        f"{SCAFFOLD_DIR}/src/__init__.py": '"""scaffold package."""\n',
        f"{SCAFFOLD_DIR}/src/main.py": (
            '"""Main entry point."""\n\n\ndef greet(name: str) -> str:\n'
            '    """Return a greeting string."""\n'
            '    return f"Hello, {name}!"\n\n\n'
            'if __name__ == "__main__":\n'
            '    print(greet("World"))\n'
        ),
        f"{SCAFFOLD_DIR}/tests/test_main.py": (
            '"""Tests for main module."""\n'
            "from scaffold.src.main import greet\n\n\n"
            "def test_greet_returns_string():\n"
            "    assert isinstance(greet('Alice'), str)\n\n\n"
            "def test_greet_contains_name():\n"
            "    assert 'Bob' in greet('Bob')\n"
        ),
    }

    os.makedirs(SCAFFOLD_DIR, exist_ok=True)
    for path, content in files.items():
        result = await editor.execute(command="create", path=path, file_text=content)
        rel = path.replace(SCAFFOLD_DIR, "scaffold")
        icon = "✅" if not result.is_error else "❌"
        print(f"  {icon}  {rel}" + (f" — {result.error}" if result.is_error else ""))

    stream.push("example-03", "tool", f"file_editor: scaffold {SCAFFOLD_DIR}")
    print()


async def step_edit_file(editor: StrReplaceEditorTool, stream: ActivityStream) -> None:
    """Demonstrate in-place str_replace editing."""
    print("✏️   Step 3: In-place file edit (str_replace) …")
    target = f"{SCAFFOLD_DIR}/src/main.py"

    result = await editor.execute(
        command="str_replace",
        path=target,
        old_str='    return f"Hello, {name}!"',
        new_str='    return f"Hello, {name}! — powered by weebot 🤖"',
    )
    if result.is_error:
        print(f"  ❌  Edit failed: {result.error}")
    else:
        stream.push("example-03", "tool", "file_editor: str_replace main.py")
        # Verify by viewing the changed file
        view = await editor.execute(
            command="view", path=target, view_range=[5, 8]
        )
        print("  ✅  Lines 5-8 after edit:")
        for line in view.output.strip().splitlines():
            print(f"       {line}")
    print()


async def step_verify(bash: BashTool, stream: ActivityStream) -> None:
    """List the scaffold tree using PowerShell."""
    print("🔍  Step 4: Verifying structure via PowerShell …")
    cmd = (
        f"Get-ChildItem -Path '{SCAFFOLD_DIR}' -Recurse "
        f"| Select-Object -ExpandProperty FullName"
    )
    try:
        result = await bash.execute(command=cmd, timeout=10)
    except Exception as exc:
        print(f"  ⚠️   Skipped (PowerShell unavailable): {exc}")
        print()
        return
    if result.is_error:
        print(f"  ⚠️   Skipped: {result.error}")
    else:
        for line in result.output.strip().splitlines():
            rel = line.replace(SCAFFOLD_DIR, "scaffold").strip()
            if rel:
                print(f"  📄  {rel}")
        stream.push("example-03", "tool", "bash: Get-ChildItem scaffold")
    print()


async def main() -> None:
    stream = ActivityStream()
    bash   = BashTool()
    editor = StrReplaceEditorTool()

    await step_system_info(bash, stream)
    await step_scaffold(editor, stream)
    await step_edit_file(editor, stream)
    await step_verify(bash, stream)

    print(f"📋  Activity log ({len(stream.recent())} events):")
    for event in stream.recent():
        print(f"    [{event.kind}] {event.message}")


if __name__ == "__main__":
    asyncio.run(main())
